### ISSUE TITLE
listenTo() vs on()/off()

### ISSUE THREAD

**Issue by ptitgraig** [ilyavolodin/eslint-plugin-backbone#35]
Hello.
That issue should be tagged as question :)
I'm much interested in your eslint backbone plugin and think that's a great initiative.

I'd like to discuss a new rule with you.
Since Backbone 0.9, the `listenTo()` method has been added. I'm thinking of a new rule that would check if the user used `listenTo()` instead of `on()` / `off()`. 

Let me know what you think.

As seen in the Backbone fundamentals book by Addy Osmani
> If you use on and off and remove views and their corresponding models at the same time, there are generally no problems. But a problem arises when you remove a view that had registered to be notified about events on a model, but you don’t remove the model or call off to remove the view’s event handler. Since the model has a reference to the view’s callback function, the JavaScript garbage collector cannot remove the view from memory. This is called a “ghost view” and is a form of memory leak which is common since the models generally tend to outlive the corresponding views during an application’s lifecycle.

**Comment by ilyavolodin** [comment]
I was thinking about a rule like this, but there are limitations as to what linter can do. Since the code is not compiled, but just parsed, I don't really know which variables have Backbone models/objects assigned to them. So if I check for general `on` and `off` function calls, it will flag statements like this:
```
this.$el.on("click", function() {...});
```
I can create a rule that only checks `on` and `off` on `this.model` inside views. Do you think that would be sufficient?

**Comment by ptitgraig** [comment]
Hello.
That's right I didn't think about that. I'd say that we're not supposed to use directly jQuery event binding in Backbone as events should be declared at View level. However i believe that would be a bit too harsh for a developer.
Indeed, a rule that check `on` and `off` on `this.model` would be a good way to handle this.

**Comment by ilyavolodin** [comment]
Any suggestion for the name of the rule? I'm having a hard time coming up with one. It should start with `no-view-`.

**Comment by ptitgraig** [comment]
:) having a hard time too.
What do you think of `no-view-onoff-binding` ? Or maybe a funny name like `no-view-ghostify` ?
