### ISSUE TITLE
Rule suggestion : events hash on top

### ISSUE THREAD

**Issue by ptitgraig** [ilyavolodin/eslint-plugin-backbone#36]
Hello.
This issue should be tagged as question.
What do you think a a rule that would check if the events hash is on top a a view ?

Events hash on top a a view improve code readability since the reader quickly know what are the possible interactions.

Thanks.

**Comment by ilyavolodin** [comment]
Do you mean this rule?: https://github.com/ilyavolodin/eslint-plugin-backbone/blob/master/docs/rules/events-on-top.md

**Comment by ptitgraig** [comment]
Yes, that's exactly that. Sorry for missing it.

**Comment by ilyavolodin** [comment]
No problem.
