### ISSUE TITLE
Switching over to eslint's RuleTester

### ISSUE THREAD

**Issue by platinumazure** [ilyavolodin/eslint-plugin-backbone#41]
I designed platinumazure/eslint-plugin-qunit largely based off of your configuration- thank you very much for providing a good example of how to get started!

That said, when I tried to get Travis CI configured, I couldn't get tests to pass there although I had no problems locally. I believe this is because Travis installs eslint@1.1.0 with the current package.json, and ESLint 1.x changed a bunch of internals and deprecated eslint-rule-tester. Although I could have clamped the ESLint devDependency at <1.0, I decided to bite the bullet and just migrate to RuleTester and up the devDependency version to >=1.0.0. I left the peerDependency version at >=0.9.0 though.

It's your call on whether to cut over or not, but my guess is any future pull requests on this repository will fail in Travis CI until you either clamp the ESLint devDependency to <1.0.0, or use the new RuleTester and update the ESLint devDependency to >=1.0.0.

**Comment by ilyavolodin** [comment]
Thanks for the issue. I was planning on changing dependencies and updating
this plugin to the latest soon. I do not currently have stable access to
the computer, but one I do, I'll upgrade everything.

**Comment by platinumazure** [comment]
I could write a pull request if you want? I'm traveling now but will be back tonight and could get one up early this week.

**Comment by ilyavolodin** [comment]
Sure if you have time, pull requests are always welcome!
