### ISSUE TITLE
"Cannot read property 'name' of undefined" in checkForBackboneType

### ISSUE THREAD

**Issue by texclayton** [ilyavolodin/eslint-plugin-backbone#42]
We have a unit test that does something similar to:
View.extend({
        initialize: function () {
            //do stuff
        }
});

This throws an exception in backbone-helper.js in checkForBackboneType because item.postfix is truthy, but object.property is undefined.

**Comment by ilyavolodin** [comment]
Thanks for the report. Yes, it's not one of the use cases that I though about. It's supposed to only get triggered by `Backbone.View.extend`.

**Comment by ilyavolodin** [comment]
Adam, can you tell me what's in your `settings` property in .eslintrc? I can't reproduce this issue, but the `checkForBackboneType` function is driven by `settings`.

**Comment by texclayton** [comment]
"settings": {
        "backbone": {
            "View": ["View"],
            "Model": []
        }
    },
