### ISSUE TITLE
package.json lacks ESLint peerDependency

### ISSUE THREAD

**Issue by platinumazure** [ilyavolodin/eslint-plugin-backbone#50]
The `package.json` of this project lacks a `peerDependencies` block with ESLint in it.

If you're not familiar with `peerDependencies`, the idea is that anyone trying to install this package as a dependency or dev dependency will get a warning if the peer dependencies are not also available elsewhere in the consuming project's dependency tree. Since this is an extension of ESLint and ESLint manages plugin hooks, it would be incorrect for this project to specify ESLint as a dependency; however, we should take advantage of NPM's functionality to warn if ESLint isn't present in the project dependency tree, since we do piggyback off of whatever ESLint is installed.

If my `no-view-qualified-jquery` pull request lands, we will need to set the ESLint peer dependency version to `^1.3.0`. If any of the rules use autofix, the peer dependency version will need to be `^1.4.0`. (And so on for any other recent ESLint features we're using.)

If this is accepted and I don't get direction to specify a different version, I'll create a pull request specifying `^1.3.0`.

**Comment by ilyavolodin** [comment]
Hmm... I thought I always had it. Very strange.

**Comment by platinumazure** [comment]
Maybe I missed it? I can take another look later. If you happen to beat me
to it and find I'm wrong, feel free to close this.
