### ISSUE TITLE
README incorrectly mentions plugin defaults, which are no longer respected in ESLint 2.0

### ISSUE THREAD

**Issue by platinumazure** [ilyavolodin/eslint-plugin-backbone#56]
Plugin default information should be removed from README or at least a note should be added to clarify that ESLint>=2.0.0 will not respect plugin defaults.

You could also remove the defaults entirely if you wanted, but I think that would be a breaking change requiring a major version bump.

**Comment by ilyavolodin** [comment]
Ahh... You are correct! Totally forgot about it. I don't think removing it would be necessary, in 2.0.0 it just wouldn't work. I should probably add config though for >2.0
