### ISSUE TITLE
Support for ESlint 2.x

### ISSUE THREAD

**Issue by darrenhaken** [ilyavolodin/eslint-plugin-backbone#57]
When I tried to use the plugin NPM complained of an unmet dependency.

**Comment by darrenhaken** [comment]
Any reason we couldn't upgrade o the new ESLint version and publish?

**Comment by platinumazure** [comment]
I think the package.json should specify `"eslint": ">=1.10.0"` instead of `"eslint": "^1.10.0"`, unless we think the plugin has consumed new, breaking functionality from ESLint that will leave our 1.x users in the dust.

**Comment by platinumazure** [comment]
@darrenhaken Just so we have a record, could you please post the exact output of what you get when you try to install? And if you could list your ESLint version as well, that would be helpful.

**Comment by ilyavolodin** [comment]
I was planning on bumping up version of ESLint in package.json, but it completely slipped my mind. I'll try to do that sometime this week and do a release of new version.

**Comment by darrenhaken** [comment]
That's great. If you want me to do it and send a PR let me know and I can do that

**Comment by ilyavolodin** [comment]
Thanks for the offer. I wanted to do some additional changes that are not documented yet. This should now be fixed.

**Comment by darrenhaken** [comment]
Thanks for fixing this off @ilyavolodin
