### ISSUE TITLE
peerDependencies are overly restrictive

### ISSUE THREAD

**Issue by brianhelba** [ilyavolodin/eslint-plugin-backbone#72]
[A recent commit](https://github.com/ilyavolodin/eslint-plugin-backbone/commit/1524e1c495af4fafa01b0189743570b50acc9b0d) made the `peerDependencies` require `eslint>=4.0.0`. Many users of `eslint-plugin-backbone` may not have upgraded to `eslint` v4 yet, and a number of well-established packages in the ESLint ecosystem (e.g. [`eslint-plugin-standard`](https://www.npmjs.com/package/eslint-plugin-standard) do not yet support v4.

While `eslint-plugin-backbone` is free to use `eslint>=4.0.0` as one of its own `devDependencies`, it should not be so restrictive about how it's used in practice.

Until it's confirmed that `eslint` v2 or v3 no longer work with  `eslint-plugin-backbone`, the `peerDependencies` should not restrict usage of earlier versions.

**Comment by ilyavolodin** [comment]
Good point. The reason why I upgraded both `devDependancies` and `peerDependancies` was because some unittests were added that use ES8, and ESLint only added support to ES8 in version 4. But you are right, that should only affect `devDependancies`.
